export const pfp = require("../assets/pfp.png")
export const darkBg = require("../assets/darkBg.png")
export const lightBg = require("../assets/lightBg.jpg")
export const icon = require("../assets/icon.png")
export const icon_light = require("../assets/icon-light.png")